# Site settings
title: امیرحسین اسلامی
email: eslami.amir76@gmail.com
description: Amirhossein Eslami's personal blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dotamir.ir" # the base hostname & protocol for your site
twitter_username: dot_amir
github_username:  dotamir
codepen_username: dot_amir
instagram_username: dot_amir

# Build settings
markdown: kramdown
